
services:
  db:
    container_name: idle-postgres
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gatherer_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
volumes:
  postgres_data:

